[package]
name = "asmdiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-demangle = "0.1"
regex = "1.6"
once_cell = "1.14"
clap = { version = "3.2", features = ["derive"] }
